### ISSUE TITLE
Reorder folder contents

### ISSUE THREAD

**Issue by sfllaw** [stuarthayhurst/alphabetical-grid-extension#1]
The contents of each folder are not being sorted by this extension, which is unfortunate.

You can find the explicit list of each folder’s contents in `org.gnome.desktop.app-folders.folders.*.apps`. Note that these are listed by their `.desktop` filenames, so they probably need to get sorted by their actual Name.

**Comment by stuarthayhurst** [comment]
Thanks, I'll look into this

**Comment by stuarthayhurst** [comment]
Well I've got something working, but it's rather hacky and I'd rather make it a little more elegant before committing it.

**Comment by stuarthayhurst** [comment]
Fixed in master

**Comment by sfllaw** [comment]
Thanks!
