### ISSUE TITLE
Improve design of settings UI

### ISSUE THREAD

**Issue by stuarthayhurst** [stuarthayhurst/alphabetical-grid-extension#10]
I think the UI could be improved to sort of reflect the settings app styling, image attached at the end. I'm not very familiar with GTK+, so my best guess is to set a margin on it so it doesn't extend to the edge, then use some css borders?

![image](https://user-images.githubusercontent.com/33733427/120291708-83bff380-c2bb-11eb-83c0-5125f57576ba.png)

**Comment by stuarthayhurst** [comment]
This [link](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-3-38/subprojects/extensions-app/js/main.js) looks promising

**Comment by stuarthayhurst** [comment]
Using GTK inspector on the extensions app shows that adding the `frame` style class to our `GtkListBox` will add a border, now we need a margin either side, like we had before.

![image](https://user-images.githubusercontent.com/33733427/120294032-b4a12800-c2bd-11eb-8484-8e6ea3beed7e.png)

**Comment by stuarthayhurst** [comment]
@daPhipz What do you think?
With a start and end margin of 12 applied, here's how it looks: (Ignore the heavy pixelation, my computer had a stroke)

![image](https://user-images.githubusercontent.com/33733427/120297613-2cbd1d00-c2c1-11eb-98c5-6917da45f003.png)

**Comment by stuarthayhurst** [comment]
New settings elements can be added below and separated with a GtkSeparator, and that should look like each row of the extensions app.

**Comment by stuarthayhurst** [comment]
I also added a label, as the settings menu still felt a little too plain. Added as a translatable string.

![image](https://user-images.githubusercontent.com/33733427/120326661-deb81180-c2e0-11eb-8b45-ba9551625e80.png)

**Comment by stuarthayhurst** [comment]
@daPhipz As I mentioned this in #8 and you haven't had a chance to respond, I'll close this if you don't have anything to add to the changes :)
Also see #12 for another change

**Comment by daPhipz** [comment]
I'm all for your proposal, it looks very nice :+1:
