### ISSUE TITLE
[Feature Request] Provide option to list folders first

### ISSUE THREAD

**Issue by daPhipz** [stuarthayhurst/alphabetical-grid-extension#2]
It would be nice if there was an option to put folders first (in alphabetical order amongst themselves), then follow with applications (again from A-Z).
What do you think?

PS: If you are planning on making anything with translatable Strings (Settings, translated log messages maybe?), ping me - I have some scripts that make handling with translations easier and know my way around the topic. I am happy to help on that front!

**Comment by stuarthayhurst** [comment]
I did have plans to add a setting to configure whether app folders mix with other apps, go to the start or go to the end. I'll ping you when I get around to implementing translated log messages and settings values, thanks :)

**Comment by daPhipz** [comment]
Thanks! I'll file a PR when I have the time, in which I will work on setting up the "backend" for translations.

**Comment by stuarthayhurst** [comment]
I'll get to this issue soon, I wanted to update some documentation and the build system first :)

**Comment by stuarthayhurst** [comment]
I was going to start work on this, but I decided I'd make a release first so I wasn't pressured for time. During testing on GNOME 40, the whole UI failed... Working on gtk-4 support right now, and it's almost ready. After that, I should be able to get to this issue next as it's the only thing left on my todo list. However, I will probably be dropping GNOME 3.38 support after this issue is fixed, as it's difficult to support GNOME 40, 3.38, GTK 3 and GTK 4 at the same time, unless this issue is painless to implement.

**Comment by daPhipz** [comment]
I think about dual booting Fedora (which is already shipping 40) and Ubuntu 21.04, my main OS.
This will enable me to do testing on 40 as well - somehow, my computer doesn't like VMs...
At least, I get zero performance and therefore usability out of them.

I had some weird Shell crashes in 3.38 as well...

**Comment by stuarthayhurst** [comment]
I test the code in a Fedora VM, testing it isn't the issue. It's implementing the same features twice and making sure they don't collide that gets annoying. If nothing else becomes an issue, I can leave GNOME 3.38 support. It's mostly just if something else breaks, I'll probably drop GNOME 3.38 support.

**Comment by stuarthayhurst** [comment]
I've got a semi-working implementation of this working for GNOME 3.38, and while writing it I'm fairly sure I've also found a way to refresh the order of the grid without reloading the shell :)

**Comment by daPhipz** [comment]
Nice!

**Comment by stuarthayhurst** [comment]
@daPhipz Everything should be working with this now in master, I'll close this once you can confirm it's working on your end.

**Comment by stuarthayhurst** [comment]
I'd also appreciate it a ton if you could update the German translation whenever you get a chance, as then I can make a release :)

**Comment by daPhipz** [comment]
Nice work! :+1:
Everything works as expected - sorry for letting you wait this long, but work has been absolute hell this week. I needed some time off on non-work hours...
I will start working on the translation now, but I think the PR will be ready tomorrow. Maybe I find some small things that could be also included in the release ;)

**Comment by stuarthayhurst** [comment]
> Everything works as expected - sorry for letting you wait this long, but work has been absolute hell this week. I needed some time off on non-work hours...

Totally fine, I develop this for fun too, no need to add more stress :)

> I will start working on the translation now, but I think the PR will be ready tomorrow. Maybe I find some small things that could be also included in the release ;)

Thanks a ton, if you find anything, let me know
