### ISSUE TITLE
[Feature Request] Add option to show favorite apps in app grid

### ISSUE THREAD

**Issue by somepaulo** [stuarthayhurst/alphabetical-grid-extension#20]
Since Gnome Shell 40 apps in the favorite list are not shown in the overall app grid by default, and there's no hidden option to make them show up anywhere. My bug report on the issue was rejected upstream, so you guys are my only hope for this feature. I believe that users should be able to use the app grid as a complete applications menu and therefore, all apps should be displayed in the grid, whether favorite ones or not. Please consider adding this feature. Pleeeease!

**Comment by stuarthayhurst** [comment]
I'll take a look at if it's feasible to add, it may be that I can't override it.

**Comment by stuarthayhurst** [comment]
After looking at this, I can't find the code stopping the favourites from being displayed. I tried adding the favourites back in when the grid is reordered, and the space is reserved for them in the grid, but they don't show up. If you can find the code that prevents them from being displayed, I'll reopen this and give it another shot :)

**Comment by somepaulo** [comment]
Could it be the code on line 314 in [appDisplay.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/appDisplay.js)?
````
// Don't duplicate favorites
this._appFavorites = AppFavorites.getAppFavorites();
this._appFavoritesChangedId =
    this._appFavorites.connect('changed', () => this._redisplay());
````

**Comment by stuarthayhurst** [comment]
I'll give this a closer look and see what I can do, thanks

**Comment by stuarthayhurst** [comment]
Line 1601 in the same file is interesting,
```
            return !this._appFavorites.isFavorite(appInfo.get_id()) &&
                this._parentalControlsManager.shouldShowApp(appInfo);

```
It's filtering out favourite apps and apps restricted by parental controls. When we add the favourite apps back to the `app-picker-layout` key, this piece of code filters it back out when the grid is loaded.

**Comment by stuarthayhurst** [comment]
I've managed to get a system in place to patch the function responsible, now I just have to reimplement the function and add this to the settings menu, but it's possible :)

**Comment by stuarthayhurst** [comment]
Fixed in master, it can be enabled from the settings menu
