### ISSUE TITLE
Appname with accent are move to the end

### ISSUE THREAD

**Issue by Aurnytoraink** [stuarthayhurst/alphabetical-grid-extension#24]
It would be more logical to have application that starts with É next to the one with an E
![image](https://user-images.githubusercontent.com/28545669/127985114-861d0e01-6bb8-40e8-b1f1-0c5cffa1a4dc.png)

**Comment by stuarthayhurst** [comment]
Thanks for catching this, I didn't have any applications to test with. Should be an easy fix, I'll patch this later today :)

**Comment by stuarthayhurst** [comment]
Fixed on master, it'll be released in the next couple of days
