### ISSUE TITLE
I translated your extension to french

### ISSUE THREAD

**Issue by Tuxman2** [stuarthayhurst/alphabetical-grid-extension#33]
Hi,

I translated your extension for french people. But I can't upload the fr.po file in your repository, so I push the file here.

Here is the file:

[fr.po.zip](https://github.com/stuarthayhurst/alphabetical-grid-extension/files/7072524/fr.po.zip)

Regards.

**Comment by stuarthayhurst** [comment]
Thanks a ton, I'll add this to the extension :)
As a tip, if you become familiar with `git` if you're not already, you can fork this repository, make the changes on your copy of the code, and then create a pull request. This means you'll be able to contribute the translations without sending files across issue tickets and you'll also appear as a contributor to the repository, so you get proper credit. It also means you'll be able to keep the French translations updated if you wish, without having to create a new issue every time and send files over.

**Comment by stuarthayhurst** [comment]
If you want, you could use the translations to practice making a pull request here:
 - Fork the repository with the button in the top right
 - Clone your fork of the repository to your computer
 - Add the translations to your copy of the code
 - Create a commit for the changes and upload them (`git add *`, `git commit` and `git push`)
 - Create a pull request for the changes. next to the issues tab

**Comment by Tuxman2** [comment]
Ok, I will look it later. ;-)

Otherwise, I was looking for this kind of extension on Gnome but it didn't exist. You did it, it's great.  

Thanks. ;-)

**Comment by stuarthayhurst** [comment]
I only have 1 issue with the translation:
```
#. Translators: Do not translate literally. If you want, you can enter your
#. contact details here: "FIRSTNAME LASTNAME <email@addre.ss>, YEAR."
#. If not, "translate" this string with a whitespace character.
#: prefs.js:81
msgid "translator-credits"
msgstr "traducteurs-crédits"
```
If you want credit for the translation in the extension, add your details like:
`msgstr "Firstname Surname <email>"`
And if you don't want credit, just use:
`msgstr " "`

**Comment by Tuxman2** [comment]
Can you let it blank ? Thanks.

**Comment by stuarthayhurst** [comment]
Yep, that's fine. Do you want me to add the translations or are you going to give it a shot later? I'm happy either way :)

**Comment by Tuxman2** [comment]
If you can add the fr.po file in your repository it would be fine because I have no time to clone your repository now.

Thanks.

Regards.

**Comment by stuarthayhurst** [comment]
Ok, thanks a ton for the translation :)
Just one last thing, do you want me to ping you when the extension is ready to be translated, or not to worry about it?

**Comment by Tuxman2** [comment]
Not worry about it. I will look from time to time. ;-)

**Comment by daPhipz** [comment]
@Tuxman2: Thanks for the translation!
I had two minor things to add, could you please check if I did everything correctly by following the link to #34 and answer my questions there?
Thanks!
