### ISSUE TITLE
Build system improvements

### ISSUE THREAD

**Issue by stuarthayhurst** [stuarthayhurst/alphabetical-grid-extension#40]
Outlined, in #39, there are a number of improvements that could be made surrounding the build system.

## Planned Changes:
 - [x] Better integration with Makefile's capabilities
 - [x] Better automatic build system testing
   - [x] Could potentially be better structured
   - [x] More coverage of the build system is also possible
 - [x] Improving the scripts in `scripts/`, potentially integrate some of them into `Makefile`
 - [x] Better organisation in `.gitignore`
 - [x] Automate updating metadata.json with `make release`
 - [x] Allow passing a different compression level to `make compress`

These will probably be summarised as "Build system improvements #39, #40" in `docs/CHANGELOG.md` when release time comes

**Comment by daPhipz** [comment]
I see that you already have done some work on this - nice! :tada: 

> Better integration with Makefile's capabilities

What do you have in mind here? My understanding of a better integration would go in the direction of #39, which you didn't want (which is totally fine). I would love to help, but bombarding you with PRs you would reject is not really helping, is it :joy:

And btw: Should anything I write sound aggressive or offended - it is 100 % not intended that way! It's just that I am not a native English speaker and maybe don't know some words that might sound nicer - so, I hope you understand that ;)

**Comment by stuarthayhurst** [comment]
> What do you have in mind here?

I'm not entirely sure to be honest. I wasn't totally on board with #39, as I was trying to keep the Makefiles similar between my projects, and I was already happy with the structure and workflow. Mostly, I mean if there's anything being done 'backwards' in the Makefile it could be corrected. I left this one to last, as I wasn't sure, and I'm also not super familiar with Makefile's less obvious features.

> And btw: Should anything I write sound aggressive or offended - it is 100 % not intended that way! It's just that I am not a native English speaker and maybe don't know some words that might sound nicer - so, I hope you understand that ;)

Totally fine, I didn't take anything as aggressive anyway :)

**Comment by daPhipz** [comment]
So what you are saying is, you want to be able to execute each step the makefile would do automatically "by hand" for debugging purposes, is that right?

**Comment by stuarthayhurst** [comment]
More or less, yes. So I guess I meant to look into any quirks or operators in Makefile that could be used to streamline the build system at all, leaving it mostly as it is.

**Comment by daPhipz** [comment]
Ah ok, got it ;)
I will see what I can come up with :rocket:

**Comment by stuarthayhurst** [comment]
Awesome, I look forward to it :)

**Comment by stuarthayhurst** [comment]
Thanks for the help with the ideas and the implementation, I probably wouldn't have got round to this otherwise

**Comment by daPhipz** [comment]
Happy to help and learn along the way :)
