### ISSUE TITLE
[Bug] Item is not part of the IconGridLayout

### ISSUE THREAD

**Issue by laontme** [stuarthayhurst/alphabetical-grid-extension#50]
**Describe the issue**
Just now i installed my ArhcLinux setup and installed gnome with my favourite extension Alphabetical App Grid and when i restarted, my app grid is empty. By enabling and disabling all extensions i ensure that problem in Alphabetical App Grid. I enabled logs in extension settings and see something like
```
JS ERROR: Error: Item [0x55fa8dc2b2e0 Gjs_ui_appDisplay_AppIcon.app-well-app ("Advanced Network Configuration")] is not part of the IconGridLayout
moveItem@resource:///org/gnome/shell/ui/iconGrid.js:891:19
moveItem@resource:///org/gnome/shell/ui/iconGrid.js:1353:29
_moveItem@resource:///org/gnome/shell/ui/appDisplay.js:1023:20
_redisplay/<@resource:///org/gnome/shell/ui/appDisplay.js:858:22
_redisplay@resource:///org/gnome/shell/ui/appDisplay.js:853:17
_redisplay@resource:///org/gnome/shell/ui/appDisplay.js:1485:15
_runDeferredWork@resource:///org/gnome/shell/ui/main.js:706:31
_runBeforeRedrawQueue@resource:///org/gnome/shell/ui/main.js:721:25
_queueBeforeRedraw/<@resource:///org/gnome/shell/ui/main.js:730:13
```

I tried to hide icon using NoDisplay=true and now error throwed by "Archive Manager"

I think problem not in specific app but in all apps

**To Reproduce**
Just install GNOME and Alphabetical App Grid?

**Expected behavior**
I expect Alphabetical App Grid in my GNOME :)

**Screenshots and logs**
https://pastes.dev/00O1RzZMVO
![image](https://user-images.githubusercontent.com/60975415/151719780-42b96385-7220-4bc4-9309-1966588c8223.png)

**System information (please complete the following information):**
 - Distro: ArchLinux
 - GNOME version: GNOME Shell 41.3
 - Extension version: 18

**Additional context**
I also noticed that my profile icons are not installable. I do it by manualy editing /var/lib/AccoutService, but this is strange

**Comment by laontme** [comment]
I just noticed that I have other extensions installed. I will try to create a clean profile and test the extension

**Comment by stuarthayhurst** [comment]
That's an interesting issue... not seen that before. I'll investigate tomorrow in a VM, I'll see if I can reproduce this when I get time. Keep me updated, thanks for the report :)

**Comment by laontme** [comment]
Issue was solved when i change kernel from linux to linux-zen. I am not sure that kernel chanign fix the problem because this is strange

**Comment by stuarthayhurst** [comment]
I can't reproduce this, it's probably a symptom of another issue, and not an issue with the extension. Can this be closed?

**Comment by laontme** [comment]
yeah. of course. this can be closed
