### ISSUE TITLE
Translation updates for GNOME 42

### ISSUE THREAD

**Issue by stuarthayhurst** [stuarthayhurst/alphabetical-grid-extension#55]
@daPhipz @Vistaus @oscfdezdz @sngvy I've been working on updating the extension for GNOME 42, the translation strings and UI should be stable now. I'm not in any hurry to get a new release out, so feel free to work on the translations whenever you have time, if at all. If any of you don't want to be pinged next time, just let me know please :)
  - There should be 7 new strings for each translation, and the Russian string has 1 extra that wasn't translated before. I've updated the files completely, so all the needs doing is filling in the translations
  - Translation `.po` files have been moved to `extension/po/`
  - You'll also notice the `translator-credits` string is gone. Translator information has been moved to `extension/credits.json`, so I can display all of them at once in the new UI
   - Nothing new has been added there information-wise, but if anyone wants be be removed from that file, just let me know and I'll get that done
@daPhipz, as you helped out several times with the build system, settings, UI and translation setup, do you want credit as a developer too? Feel free to add it yourself, or let me know and I'll do it, I'm sure you can make sense of the `credits.json` file :)

Thank you so much for all your translation efforts, it really means a lot :)

**Comment by daPhipz** [comment]
Thanks for the heads-up!
Is the `year` in `credits.json` supposed to be one year only, or can it take e.g. `"2021-2022"` as well?

**Comment by stuarthayhurst** [comment]
Should be able to take either :)
