### ISSUE TITLE
[Bug] New apps aren't sorted, instead stuck at the end of the grid until manually triggered

### ISSUE THREAD

**Issue by InklingGirl** [stuarthayhurst/alphabetical-grid-extension#63]
**Describe the issue**
The _GNOME_ app grid becomes de-alphabetised whenever a new app is installed, only re-alphabetising when this extension is turned off & on again.

**To Reproduce**
1. Install _Alphabetical App Grid_ via Web browser
2. Install any package that generates a .desktop graphical menu shortcut
3. Check _GNOME_ app grid
5. Observe that your installed apps are de-alphabetised, piling up at the end

**Expected behavior**
I expect everything to remain permanently alphabetised & that newly installed apps should be placed alphabetically.

**System information (please complete the following information)**
 - Distro: _Ubuntu 22.04 LTS Jammy Jellyfish_ w/ _Wayland_ as windowing server
 - GNOME version: _GNOME 42_
 - Extension version: `Version: 23`

**Comment by stuarthayhurst** [comment]
Can you confirm that moving an app to a new position will also trigger the correct order, instead of toggling the extension? I'll get to fixing this as soon as I can, thanks for the report :)

**Comment by InklingGirl** [comment]
> Can you confirm that moving an app to a new position will also trigger the correct order, instead of toggling the extension?

Yes @stuarthayhurst, moving an app's position resets the whole grid to an alphabetical state, which is much easier. That & toggling the extension are the only ways. I hope there's an easy fix in your troubleshooting of the JS!

**Comment by PJ-Singh-001** [comment]
After I install a new app, it is shown at the end of the list.

If I turn the extension off and on, the apps become sorted alphabetically.
However, if I log out and log back-in, the apps are no longer sorted alphabetically.

I also have the same issue if I trigger the resorting by moving the app.
When I log out and log back-in, the apps are no longer sorted alphabetically.

**Comment by stuarthayhurst** [comment]
> After I install a new app, it is shown at the end of the list.
> 
> If I turn the extension off and on, the apps become sorted alphabetically. However, if I log out and log back-in, the apps are no longer sorted alphabetically.
> 
> I also have the same issue if I trigger the resorting by moving the app. When I log out and log back-in, the apps are no longer sorted alphabetically.

I'll tackle this in #65, as it's a probably different cause showing the same symptom

**Comment by stuarthayhurst** [comment]
I got a bit of time to troubleshoot this, and the extension applies the reorder, it's just overridden or ignored when the app grid opens for some reason. Potentially I could delay the reorder until the app grid is reopened, but I can't find a reliable way to detect the app grid has been opened.

**Comment by stuarthayhurst** [comment]
Do either of you happen to have any extensions that mess with the dash installed? I think they might be conflicting with one of the signals this extension detects. Ideally, I wouldn't have to connect to the signal, but I might be able to make a workaround if that's what's causing it.

**Comment by InklingGirl** [comment]
I'll try to check.

**Comment by stuarthayhurst** [comment]
> I'll try to check.

Dash-to-dock is the most likely culprit, as that caused some issues on my system

**Comment by InklingGirl** [comment]
> Dash-to-dock

I don't have this, but I do have Dash to Panel!

**Comment by stuarthayhurst** [comment]
Good to know, I'll see if I can write a work around when I get a bit more time :)

**Comment by InklingGirl** [comment]
This may be overkill or may not be required anymore, but these are all my extensions @stuarthayhurst:
![2023-01-29_12-06](https://user-images.githubusercontent.com/9910447/215298362-ee27a653-8731-489f-aaf8-1f3351ee0298.png)
As far as I can tell _ArcMenu_ & _Dash to Panel_ are the 2 extensions that specifically mess w/ the dash.

**Comment by stuarthayhurst** [comment]
So I read through the source for dash-to-dock (triggers this on my machines) and dash-to-panel, and they both replace `imports.ui.Dash`. This extension connects to `Dash.showAppsButton`, so when these larger extensions load after my lighter weight one, they replace `Dash`, and this extension is no longer actually connected to the right signal to trigger a reorder. I'll try find a way to reconnect to the right signal when it detects that `Dash` has been replaced, then push this to a branch for testing.

**Comment by stuarthayhurst** [comment]
If you're familiar with git, I've pushed a fix to the `fix-dash-test` branch, use `make clean install` and then reload GNOME. You'll need the build dependencies in the README too. Alternatively, I attached a built copy, if you'd rather install from that. Same process as any other GNOME extension. [AlphabeticalAppGrid@stuarthayhurst.shell-extension.zip](https://github.com/stuarthayhurst/alphabetical-grid-extension/files/10913488/AlphabeticalAppGrid%40stuarthayhurst.shell-extension.zip)

If that sorts the problem for you, I'll merge the fix and push a new release soonish.

**Comment by InklingGirl** [comment]
Thank you for your work, please give me a couple days to get around to it & I'll report back.

**Comment by InklingGirl** [comment]
Works perfectly @stuarthayhurst! I installed a new program & it was immediately alphabetised correctly in the grid view.

**Comment by stuarthayhurst** [comment]
Amazing, thanks for testing this and sorry for the delay in fixing this, but I'm glad it's sorted now

**Comment by stuarthayhurst** [comment]
Fixed on master #77

**Comment by InklingGirl** [comment]
It's no worries, thanks for getting it done.
