### ISSUE TITLE
[Bug] Flatpaks are not sorted

### ISSUE THREAD

**Issue by Ascii67** [stuarthayhurst/alphabetical-grid-extension#71]
**Describe the issue**
When opening the app grid, the installed flatpaks always appear on the last position.

**To  Reproduce**
1. Install a flatpak
2. Reboot your machine
3. Open the app grid

**Expected behavior**
The flatpaks should be sorted. They only get sorted when moving a random application to another place.

**System information (please complete the following information):**
 - Distro: Ubuntu 22.04
 - GNOME version: GNOME Shell 42.2
 - Extension version 24

**Comment by stuarthayhurst** [comment]
Thanks for the report, is this specific to flatpak apps?

**Comment by Ascii67** [comment]
I only use flatpaks and .deb packages, so I unfortunately don't know.
