### ISSUE TITLE
[Feature request] Add GNOME 43 support

### ISSUE THREAD

**Issue by git-Hmmm** [stuarthayhurst/alphabetical-grid-extension#72]
**Describe the idea or feature you'd like**
I want this extension to be functional in gnome 43

**Is your feature request related to a problem? Please describe.**
nope

**Additional context**
nope

**Comment by stuarthayhurst** [comment]
I'll sort this when I have some spare time, I'm quite busy at the moment, and also have another extension to port :)

**Comment by git-Hmmm** [comment]
@stuarthayhurst Thanks btw it won't take much time because I changed the manifest version to 43 and that's it, it seems to work fine.

**Comment by stuarthayhurst** [comment]
Oh that's good to hear, I wasn't sure, as the [port guide](https://gjs.guide/extensions/upgrading/gnome-shell-43.html#app-display) mentions changes to the app display, which is used by this extension
Thanks for giving this a test :)

**Comment by stuarthayhurst** [comment]
Gave everything a test, looks good out-of-the-box. I'll push an update in a week or so to make use of new GNOME 43 features, but I'll make a release for now with just the metadata change.

Fixed on master
