### ISSUE TITLE
[Bug] Conflict with «AntiMicroX»

### ISSUE THREAD

**Issue by Skaamit** [stuarthayhurst/alphabetical-grid-extension#73]
**Describe the issue**
I use «Fedora Linux 37» with an extension «Alphabetical App Grid» and «AntiMicroX» ( [GitHub](https://github.com/AntiMicroX) ) . At first everything was OK but now happening this.

https://i.imgur.com/lKAeWvF.png

App Grid and an extension itself are broken.

**System information (please complete the following information):**
- Fedora Linux 37
- GNOME 43.2
- Kernel: 6.0.12-300.fc37.x86_64
- Shell: bash 5.2.9
- LENOVA IdeaPad 5-14ITL05

**Comment by stuarthayhurst** [comment]
Interesting, I'll take a look when I get time, thanks for the report :)

**Comment by stuarthayhurst** [comment]
This might be fixed on `master`

If you clone master can you do the following please: (you might need `gettext` installed)
```
make build
make install
```
Then reboot to make sure it took effect

**Comment by stuarthayhurst** [comment]
Might be fixed in the latest version just released, let me know if it's still an issue :)

**Comment by stuarthayhurst** [comment]
Closing, feel free to re-open if this still affects anyone with the latest version (v27)
