### ISSUE TITLE
feature-request: Add GNOME 44 support

### ISSUE THREAD

**Issue by git-Hmmm** [stuarthayhurst/alphabetical-grid-extension#76]
### Describe the idea or feature you'd like
It would be beneficial to have this extension be functional in gnome 44 as the beta phase has already begun.

### Is your feature request related to a problem? Please describe.
nope

### Additional context
nope

**Comment by stuarthayhurst** [comment]
Do you know of any distros that are packaging the beta yet? GNOME OS is near unusable for testing development versions of extensions.

I don't know how much time I'll have if this doesn't work immediately, but I'll try any get something ready before the official release.

**Comment by stuarthayhurst** [comment]
Gave it a quick test on GNOME OS Nightly, the extensions works fine for now, but there are some warnings about deprecated behaviour. I'll fix these warnings and update the metadata to enable official support, shouldn't be that much work :)

**Comment by git-Hmmm** [comment]
thank you so much 🥰
it means a lot

**Comment by stuarthayhurst** [comment]
Fixed the warning, I've added GNOME 44 support to the `master` branch. I'm hesitant to push a release yet, as things could still change before the full release, but it's working for now.

Closing this issue, but feel free to re-open it if you discover issues further down the line :)
