### ISSUE TITLE
[Feature request] [Enhancement] Folders first

### ISSUE THREAD

**Issue by 0Raik** [stuarthayhurst/alphabetical-grid-extension#80]
**Is your feature request related to a problem?**
Yes. Folders and apps get mixed up. Its like having a file explorer mixing folders and files. Doesn't look right.

**Describe the solution you'd like**
Folders alphabetically first. Then apps. Nirvana :smile: 

**Describe alternatives you've considered**
Making it myself. But I'm no programmer :cry: 

**Can you work on it?**
See above :disappointed: 

**Additional context**
I live with only folders in my application drawer because apps there just break Zen :yin_yang: :sweat_smile: 

![Screenshot from 2023-04-21 06-14-42](https://user-images.githubusercontent.com/5239948/233632838-f8a538bd-5d5b-45ac-88e3-52e0f738b322.png)

**Comment by stuarthayhurst** [comment]
Have you tried setting "Position of ordered folders" in the extension's settings to the start?

**Comment by 0Raik** [comment]
Thank you so much!!!
Been living like this for so long. I personally blame my current theme. These days we got the huge mess of GTK3 and GTK4 theming nightmare and mine was too dark I could not see the drop-down menu for the life of me.

Personally prefer multiple choice option selection just like school tests :smile: 
![Screenshot from 2023-04-21 17-59-26](https://user-images.githubusercontent.com/5239948/233750578-6b292a3c-9a8b-4cb7-95c8-7619ffa43d02.png)

Thank you so much for your time and patience. Have a great day and :1st_place_medal:
