### ISSUE TITLE
[Bug] Conflict with Favourites in AppGrid

### ISSUE THREAD

**Issue by IndrekHaav** [stuarthayhurst/alphabetical-grid-extension#87]
**Describe the issue**
The extension seems to conflict with [Favourites in AppGrid](https://extensions.gnome.org/extension/4485/favourites-in-appgrid/). If AAG is enabled, then FiAG doesn't work. Disabling AAG doesn't make FiAG work. Both work only if FiAG is enabled first (after a reboot or logout/login).

**To Reproduce**
1. Disable all extensions
2. Log out and back in
3. Enable Alphabetical App Grid
4. Enable Favourites in AppGrid
5. Observe that FiAG doesn't work

**Expected behavior**
Both extensions work as intended.

**System information (please complete the following information):**
 - Distro: Arch (fully up-to-date)
 - GNOME version: 45.1
 - Extension version: 36

**Additional context**
Initially reported issue here: https://gitlab.gnome.org/harshadgavali/favourites-in-appgrid/-/issues/6

**Comment by IndrekHaav** [comment]
Ran the command after a fresh boot with both extensions enabled, logging enabled in Alphabetical App Grid settings.

https://pastebin.com/8QaRaLL8

**Comment by stuarthayhurst** [comment]
Hm, nothing useful in the log, I guess this is probably just a case of Alphabetical App Grid overwriting the changes the other extension made.

I thought the InjectionManager should prevent that, so either we need to adjust our usage of it, or it needs to be fixed upstream.

**Comment by stuarthayhurst** [comment]
Can you test the current version in `master` please? You don't need the PR I linked above, this should be enough

**Comment by IndrekHaav** [comment]
Seems to be fixed, I repeatedly disabled and enabled both extensions in different order, and both worked fine.

**Comment by stuarthayhurst** [comment]
Brilliant, thanks for testing :)
