### ISSUE TITLE
"gschemas.compiled" not found

### ISSUE THREAD

**Issue by andreasoragna** [stuarthayhurst/alphabetical-grid-extension#92]
**ISSUE**
Installed the git version of the extension from AUR. The extension does not work.

**LOG** 

When trying to open the preferences dialogue I get this message:

GLib.FileError: Apertura del file «/usr/share/gnome-shell/extensions/AlphabeticalAppGrid@stuarthayhurst/schemas/gschemas.compiled» non riuscita: open() non riuscita: File o directory non esistente

Stack trace:
  getSettings@resource:///org/gnome/Shell/Extensions/js/extensions/sharedInternals.js:100:53
  fillPreferencesWindow@file:///usr/share/gnome-shell/extensions/AlphabeticalAppGrid@stuarthayhurst/prefs.js:145:79
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:126:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**SYSTEM INFORMATION**
 - Distro: Arch Linux
 - GNOME version: GNOME Shell 46
 - Extension version 39

**Comment by stuarthayhurst** [comment]
This is a problem with the distro packaging. Older versions of GNOME required the `gschemas.compiled` file to be provided, but this caused problems on some architectures, so now only the source file is provided, and it's up to the Shell to compile it on install. If the extension is installed with `gnome-extensions install`, or from extensions.gnome.org then it's done automatically, but if the distro's packaging just unzips the bundle and copies the file, the schemas probably won't be compiled.

You should probably report this to the maintainer of that package, and for now you can just install from here, or from GNOME's extensions website :)
